version: 2.1

jobs:
    build:
        docker:
            - image: circleci/node:latest

        working_directory: ~/repo

        steps:
            - checkout

            - restore_cache:
                  keys:
                      - dependency-cache-1-{{ checksum "yarn.lock" }}

            - run: npm install

            - save_cache:
                  paths:
                      - node_modules
                  key: dependency-cache-1-{{ checksum "yarn.lock" }}

            - persist_to_workspace:
                  root: "."
                  paths:
                      - ./*
                      - node_modules
                      - yarn.lock
                      - src

    lint-markdownlint:
        docker:
            - image: circleci/node:latest

        working_directory: ~/repo

        steps:
            - checkout

            - attach_workspace:
                  at: "."

            - run: yarn run lint:markdownlint

    lint-tslint:
        docker:
            - image: circleci/node:latest

        working_directory: ~/repo

        steps:
            - checkout

            - attach_workspace:
                  at: "."

            - run: yarn run lint:tslint

    test-mutation:
        docker:
            - image: circleci/node:latest

        working_directory: ~/repo

        steps:
            - checkout

            - attach_workspace:
                  at: "."

            - run: yarn run test:mutation

    test-unit:
        docker:
            - image: circleci/node:latest

        working_directory: ~/repo

        steps:
            - checkout

            - attach_workspace:
                  at: "."

            - run: yarn run test:unit

    tsc:
        docker:
            - image: circleci/node:latest

        working_directory: ~/repo

        steps:
            - checkout

            - attach_workspace:
                  at: "."

            - run: yarn run tsc

workflows:
    version: 2
    commit:
        jobs:
            - build
            - lint-markdownlint:
                  requires:
                      - build
            - lint-tslint:
                  requires:
                      - build
            - test-mutation:
                  requires:
                      - build
            - test-unit:
                  requires:
                      - build
            - tsc:
                  requires:
                      - build
