version: 2.1

jobs:
    dependencies:
        docker:
            - image: circleci/node:latest

        working_directory: ~/repo

        steps:
            - checkout

            - restore_cache:
                  keys:
                      - dependency-cache-2-{{ checksum "yarn.lock" }}

            - run: yarn

            - save_cache:
                  paths:
                      - node_modules
                  key: dependency-cache-2-{{ checksum "yarn.lock" }}

            - persist_to_workspace:
                  root: "."
                  paths:
                      - ./*
                      - node_modules
                      - yarn.lock
                      - src

    lint-markdownlint:
        docker:
            - image: circleci/node:latest

        working_directory: ~/repo

        steps:
            - checkout

            - attach_workspace:
                  at: "."

            - run: yarn run lint:markdownlint

    lint-eslint:
        docker:
            - image: circleci/node:latest

        working_directory: ~/repo

        steps:
            - checkout

            - attach_workspace:
                  at: "."

            - run: yarn run lint:eslint

    publish:
        docker:
            - image: circleci/node:latest

        working_directory: ~/repo

        steps:
            - checkout

            - attach_workspace:
                  at: "."

            - run: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc

            - run: npm publish || exit 0

    test-mutation:
        docker:
            - image: circleci/node:latest

        working_directory: ~/repo

        steps:
            - checkout

            - attach_workspace:
                  at: "."

            - run: ls -lR src

            - run: yarn run test:mutation

    test-unit:
        docker:
            - image: circleci/node:latest

        working_directory: ~/repo

        steps:
            - checkout

            - attach_workspace:
                  at: "."

            - run: yarn run test:unit

    tsc:
        docker:
            - image: circleci/node:latest

        working_directory: ~/repo

        steps:
            - checkout

            - attach_workspace:
                  at: "."

            - run: yarn run tsc

            - persist_to_workspace:
                  root: "."
                  paths:
                      - src

workflows:
    version: 2
    commit:
        jobs:
            - dependencies
            - lint-markdownlint:
                  requires:
                      - dependencies
            - lint-eslint:
                  requires:
                      - dependencies
            - publish:
                  filters:
                      branches:
                          only: main
                  requires:
                      - tsc
            - test-mutation:
                  requires:
                      - tsc
            - test-unit:
                  requires:
                      - dependencies
            - tsc:
                  requires:
                      - dependencies
