version: 2
jobs:
    build:
        docker:
            - image: circleci/node:latest

        working_directory: ~/repo

        steps:
            - checkout

            - restore_cache:
                  keys:
                      - dependency-cache-{{ checksum "yarn.lock" }}
                      - dependency-cache-

            - run: yarn

            - save_cache:
                  paths:
                      - node_modules
                  key: dependency-cache-{{ checksum "yarn.lock" }}

            - run: yarn run verify

workflows:
    version: 2
    build_and_end_to_end:
        jobs:
            - build
