description: Prepares the repo for a typical CI job

name: Prepare

runs:
  steps:
    - uses: pnpm/action-setup@26f6d4f2c533a43e6b5da0b4a5dd983f98f7b49a # v6
    - uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6
      with:
        cache: pnpm
        node-version: "24"
    - run: pnpm install --frozen-lockfile
      shell: bash
  using: composite
