description: Prepares the repo for a typical CI job

name: Prepare

runs:
  steps:
    - name: Install pnpm
      uses: pnpm/action-setup@v3
      with:
        run_install: false
    - name: Install Node.js
      uses: actions/setup-node@v4
      with:
        cache: pnpm
        cache-dependency-path: "pnpm-lock.yaml"
        node-version: "20"
    - name: Install dependencies
      run: pnpm install --frozen-lockfile
      shell: bash
  using: composite
