description: Prepares the repo for a typical CI job

name: Prepare

runs:
  steps:
    - uses: pnpm/action-setup@0977fd99725f1db4007ccb2928dbb4e90d06cc86 # v6
    - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7
      with:
        cache: pnpm
        node-version: "22"
    - run: pnpm install --frozen-lockfile
      shell: bash
  using: composite
