jobs:
  accessibility_alt_text_bot:
    if: ${{ !endsWith(github.actor, '[bot]') }}
    runs-on: ubuntu-latest
    steps:
      - uses: github/accessibility-alt-text-bot@34208bfa7d76a87c500c9d0cb08567d2f13636d3 # v1.6.0

name: Accessibility Alt Text Bot

on:
  issue_comment:
    types:
      - created
      - edited
  issues:
    types:
      - edited
      - opened
  pull_request:
    types:
      - edited
      - opened

permissions:
  issues: write
  pull-requests: write
