jobs:
  accessibility_alt_text_bot:
    if: ${{ !endsWith(github.actor, '[bot]') }}
    runs-on: ubuntu-latest
    steps:
      - uses: github/accessibility-alt-text-bot@7e895d46677f15841def9acef1239ea7c12593a5 # v1.7.3
    permissions:
      issues: write
      pull-requests: write

name: Accessibility Alt Text Bot

on:
  issue_comment:
    types:
      - created
      - edited
  issues:
    types:
      - edited
      - opened
  pull_request:
    types:
      - edited
      - opened

permissions: {}
