jobs:
  contributors:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6
        with:
          fetch-depth: 0
      - uses: ./.github/actions/prepare
      - env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        uses: JoshuaKGoldberg/all-contributors-auto-action@587a3a5844b0104abb911a69a1a84ec645292f5e # v0.6.0

name: Contributors

on:
  push:
    branches:
      - main
