jobs:
  lint_packages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5
      - uses: ./.github/actions/prepare
      - run: pnpm lint:packages

name: Lint Packages

on:
  pull_request: ~
  push:
    branches:
      - main
