jobs:
  lint_packages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
      - uses: ./.github/actions/prepare
      - run: pnpm lint:packages

name: Lint Packages

on:
  pull_request: ~
  push:
    branches:
      - main
