jobs:
  lint_spelling:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
      - uses: ./.github/actions/prepare
      - run: pnpm lint:spelling

name: Lint Spelling

on:
  pull_request: ~
  push:
    branches:
      - main
