jobs:
  pr_review_requested:
    permissions:
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - run: |
          gh pr edit --remove-label "status: waiting for author"

name: PR Review Requested

on:
  pull_request:
    types:
      - review_requested

permissions: {}
