name: Push CI

jobs:
    ci:
        runs-on: ubuntu-latest
        steps:
            - uses: Codecademy/run-on-yarn@v1
              with:
                  command: ${{ matrix.command }}

        strategy:
            fail-fast: false
            matrix:
                command: ["format:verify", "lint:eslint", "lint:markdownlint", "test:mutation", "test:unit", "tsc"]

on: push
