name: Push CI

jobs:
    ci:
        runs-on: ubuntu-latest
        steps:
            - uses: Codecademy/run-on-yarn@v1
            - run: yarn ${{ matrix.command }}

        strategy:
            fail-fast: false
            matrix:
                command: ["compile", "format:verify", "lint:eslint", "lint:markdownlint", "test:unit"]

    mutations:
        runs-on: ubuntu-latest
        steps:
            - uses: Codecademy/run-on-yarn@v1
            - run: yarn compile
            - run: yarn test:mutation

on:
    push:
        branches:
            - main
    pull_request:
