name: Push CI

jobs:
    ci:
        runs-on: ubuntu-latest
        steps:
            - uses: Codecademy/run-on-yarn@v2
              with:
                  command: ${{ matrix.command }}
                  node-version: 20

        strategy:
            fail-fast: false
            matrix:
                command: ["compile", "lint:eslint", "lint:markdownlint", "test:unit"]

    mutations:
        runs-on: ubuntu-latest
        steps:
            - uses: Codecademy/run-on-yarn@v2
              with:
                  command: compile
                  node-version: 20
            - run: yarn test:mutation

on:
    push:
        branches:
            - main
    pull_request:
