jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4
      - uses: ./.github/actions/prepare
      - run: pnpm run test --coverage
      - name: Codecov
        uses: codecov/codecov-action@18283e04ce6e62d37312384ff67231eb8fd56d24 # v5
        with:
          flags: unit

name: Test

on:
  pull_request: ~
  push:
    branches:
      - main
