jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - uses: ./.github/actions/prepare
      - run: pnpm run test --coverage
      - name: Codecov
        uses: codecov/codecov-action@0da7aa657d958d32c117fc47e1f977e7524753c7 # v5
        with:
          flags: unit

name: Test

on:
  pull_request: ~
  push:
    branches:
      - main
