jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - uses: ./.github/actions/prepare
      - run: pnpm run test --coverage
      - name: Codecov
        uses: codecov/codecov-action@0565863a31f2c772f9f0395002a31e3f06189574 # v5
        with:
          flags: unit

name: Test

on:
  pull_request: ~
  push:
    branches:
      - main
