jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - uses: ./.github/actions/prepare
      - run: pnpm run test --coverage
      - name: Codecov
        uses: codecov/codecov-action@e79a6962e0d4c0c17b229090214935d2e33f8354 # v6
        with:
          flags: unit

name: Test

on:
  pull_request: ~
  push:
    branches:
      - main
