jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - uses: ./.github/actions/prepare
      - run: pnpm run test --coverage
      - name: Codecov
        uses: codecov/codecov-action@7f8b4b4bde536c465e797be725718b88c5d95e0e # v5
        with:
          flags: unit

name: Test

on:
  pull_request: ~
  push:
    branches:
      - main
