jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
      - uses: ./.github/actions/prepare
      - run: pnpm run test:mutation --coverage --no-file-parallelism --testTimeout 10000
      - name: Codecov
        uses: codecov/codecov-action@fb8b3582c8e4def4969c97caa2f19720cb33a72f # v7
        with:
          flags: mutation

name: Test Mutation

on:
  pull_request: ~
  push:
    branches:
      - main
