jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5
      - uses: ./.github/actions/prepare
      - run: pnpm run test:mutation --coverage --no-file-parallelism
      - name: Codecov
        uses: codecov/codecov-action@5a1091511ad55cbe89839c7260b706298ca349f7 # v5
        with:
          flags: mutation

name: Test Mutation

on:
  pull_request: ~
  push:
    branches:
      - main
